"""Where in each block the interesting things are - the player's own two maps, read.

Generated by ``tools/build-fieldnotes.py`` from the screenshots in ``docs/evidence/``;
edit that script rather than this file. The two tables say where *inside* a block a mark
sits, as a three-by-three position: the horizontal part is ``L``/``C``/``R`` and the
vertical part is ``U``/``D``, left out on the middle row - so ``RU`` is the top-right of
the block, ``L`` the left edge at mid height, ``C`` the middle.

* :data:`BANDIT_SPAWNS` - where the ``6 x Bandits`` group appears in that block
  (the player's *Bandits Spawn Locations* map, 2026-10-07);
* :data:`WALLS` - the wall a boss can be trapped against, prefixed ``W``
  (their *Boss Fighting Map*, same day). Green dots on that map are the player's own
  positions and are ignored.

Both are answered per block, and a row shows one note: the bandit one when the row is a
bandit spawn, the wall one otherwise. The tables are keyed by the game's own block
coordinates, anchored on the block the player named - the bottom-right-most dot of the
bandit map, ``1058,1019``.
"""

from __future__ import annotations

#: block -> position of the `6 x Bandits` spawn inside it
BANDIT_SPAWNS: dict[tuple[int, int], str] = {
    (1051, 1016): "CD",
    (1052, 1016): "CU",
    (1052, 1017): "CU",
    (1052, 1018): "RD",
    (1053, 1016): "L",
    (1053, 1017): "LU",
    (1053, 1018): "R",
    (1053, 1019): "CU",
    (1054, 1016): "L",
    (1054, 1018): "CU",
    (1054, 1019): "R",
    (1055, 1016): "C",
    (1055, 1017): "R",
    (1055, 1018): "RU",
    (1055, 1019): "R",
    (1056, 1016): "LU",
    (1056, 1017): "R",
    (1056, 1018): "C",
    (1056, 1019): "R",
    (1057, 1013): "CU",
    (1057, 1014): "RU",
    (1057, 1015): "LU",
    (1057, 1016): "RU",
    (1057, 1017): "L",
    (1057, 1018): "R",
    (1057, 1019): "L",
    (1058, 1014): "C",
    (1058, 1015): "L",
    (1058, 1016): "L",
    (1058, 1019): "CD",
}

#: block -> position of the wall to trap a boss against, `W` prefixed
WALLS: dict[tuple[int, int], str] = {
    (1052, 1016): "WRD",
    (1052, 1018): "WLU",
    (1053, 1016): "WR",
    (1053, 1017): "WCU",
    (1053, 1018): "WL",
    (1053, 1019): "WC",
    (1054, 1016): "WL",
    (1054, 1018): "WCD",
    (1055, 1016): "WC",
    (1055, 1018): "WR",
    (1056, 1017): "WCU",
    (1056, 1018): "WRD",
    (1056, 1019): "WL",
    (1057, 1013): "WR",
    (1057, 1014): "WRU",
    (1057, 1015): "WCD",
    (1057, 1016): "WRD",
    (1057, 1017): "WRU",
    (1057, 1018): "WCD",
    (1057, 1019): "WC",
    (1058, 1015): "WLD",
    (1058, 1016): "WRD",
    (1058, 1019): "WLU",
}


def bandit_remark(block) -> str:  # noqa: ANN001
    """Where the bandits stand in this block, or an empty string."""
    return BANDIT_SPAWNS.get((block.x, block.y), "")


def wall_remark(block) -> str:  # noqa: ANN001
    """The wall to trap a boss against in this block, or an empty string."""
    return WALLS.get((block.x, block.y), "")


def remark_for(block, bandits: bool) -> str:  # noqa: ANN001
    """The one field note a row gets: the bandit spot for a bandit row, else the wall.

    One, not two: a block can carry both, and two remarks on one line would push the
    coordinate and the bearing - the fields the row exists for - out of the strip.
    """
    return bandit_remark(block) if bandits else wall_remark(block)
